### 1.) Create a Python program to sort an array in descending order based on the values ?

In [7]:
def sort_descending(arr):
    return sorted(arr, reverse=True)


def validate_input(user_input):
    try:
        return list(map(int, user_input.split()))
    except ValueError:
        print("Invalid input! Please enter only numbers separated by spaces.")
        return None


def main():
    user_input = input("Enter numbers: ")
    arr = validate_input(user_input)
    if arr is None:
        return
    sorted_arr = sort_descending(arr)
    print("Sorted array in descending order:", sorted_arr)


if __name__ == "__main__":
    main()

Invalid input! Please enter only numbers separated by spaces.


### Create a NumPy Array

In [8]:
import numpy as np

my_list = [3, 4, 5]
print(my_list)
my_array = np.array(my_list)
print(my_array)

[3, 4, 5]
[3 4 5]


In [9]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arange = np.arange(10)
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
randome = np.random.rand(5)
print(randome)

[0.59607364 0.12205895 0.23469984 0.082727   0.0178926 ]


## Array Operators

### Arithmetic Operators

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = a + b
print(sum)

[5 7 9]


In [15]:
difference = b - a
product = a * b
quotient = a / b
print(difference)
print(product)
print(quotient)

[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Matrix Multiplication

In [17]:
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[5, 6], [7, 8]])
product = np.dot(matrix1, matrix2)
print(product)

[[5 6]
 [7 8]]
