### 1.) Create a Python program to sort an array in descending order based on the values ?

In [1]:
def sort_descending(arr):
    return sorted(arr, reverse=True)


def validate_input(user_input):
    try:
        return list(map(int, user_input.split()))
    except ValueError:
        print("Invalid input! Please enter only numbers separated by spaces.")
        return None


def main():
    user_input = input("Enter numbers: ")
    arr = validate_input(user_input)
    if arr is None:
        return
    sorted_arr = sort_descending(arr)
    print("Sorted array in descending order:", sorted_arr)


if __name__ == "__main__":
    main()

Sorted array in descending order: []


### Create a NumPy Array

In [2]:
import numpy as np

my_list = [3, 4, 5]
print(my_list)
my_array = np.array(my_list)
print(my_array)

[3, 4, 5]
[3 4 5]


In [9]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arange = np.arange(10)
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
randome = np.random.rand(5)
print(randome)

[0.59607364 0.12205895 0.23469984 0.082727   0.0178926 ]


## Array Operators

### Arithmetic Operators

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = a + b
print(sum)

[5 7 9]


In [15]:
difference = b - a
product = a * b
quotient = a / b
print(difference)
print(product)
print(quotient)

[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Matrix Multiplication

In [17]:
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[5, 6], [7, 8]])
product = np.dot(matrix1, matrix2)
print(product)

[[5 6]
 [7 8]]


### Array Indexing and Slicing

In [22]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


### Array Manipulation

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


### Joining Multiple Arrays

In [28]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated = np.concatenate((array1, array2))
print(concatenated)

[1 2 3 4 5 6]


### Random Number Generation

In [29]:
randome = np.random.rand(5)
print(randome)

[0.01845787 0.9574303  0.0970232  0.1370399  0.9526201 ]


In [3]:
randome = np.random.randint(1, 100, 5)
print(randome)

[58 80 39 56 24]


### 3.) Create a 1D NumPy array with values ranging from 10 to 50 (inclusive). Then, reverse the array

In [4]:
import numpy as np

start_value = int(input("Enter the start value: "))
end_value = int(input("Enter the end value: "))
arr = np.arange(start_value, end_value + 1)
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67]
Reversed array: [67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45]


### 4.) Create a 1D NumPy array with values ranging from 1 to 12. Then, reverse the array. Reshape it into a 3*4 matrix

In [5]:
import numpy as np

arr = np.arange(1, 13)
reversed_arr = arr[::-1]
reshaped_matrix = reversed_arr.reshape(3, 4)
print("Reversed array:", reversed_arr)
print("Reshaped 3x4 matrix:\n", reshaped_matrix)

Reversed array: [12 11 10  9  8  7  6  5  4  3  2  1]
Reshaped 3x4 matrix:
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### 5.) Create a 1D array arr = [3, 7, 9, 12, 15]. Extract only the elements that are greater than 10

In [6]:
import numpy as np

arr = np.array([3, 7, 9, 12, 15])
greater_than_10 = arr[arr > 10]
print("Elements greater than 10:", greater_than_10)

Elements greater than 10: [12 15]


### 6.) Create a 2x3 matrix matrix = [[1, 2, 3], [4, 5, 6]]. Add 10 to each element using broadcasting

In [7]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = matrix + 10
print("Matrix after adding 10 to each element:\n", result)

Matrix after adding 10 to each element:
 [[11 12 13]
 [14 15 16]]


## Pandas

### The Series Data Structure

In [11]:
import pandas as pd

data = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64


### DataFrame Data Structure

In [12]:
data = {'Name': ['Tom', 'Jerry', 'Mickey'], 'Age': [20, 21, 22]}
df = pd.DataFrame(data)
print(df)

     Name  Age
0     Tom   20
1   Jerry   21
2  Mickey   22


## Data Loading and Handling

### Reading Data

In [ ]:
pd.read_csv()
pd.read_excel()
pd.read_sql()

In [20]:
import pandas as pd

df = pd.read_csv("file.csv")
print(df.head())

      Name  Age    Country
0    Alice   25        USA
1      Bob   30     Canada
2  Charlie   22         UK
3    David   28  Australia
4      Eve   35    Germany


In [21]:
print(df.info())  # Summary of the dataframes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     5 non-null      object
 1   Age      5 non-null      int64 
 2   Country  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
None


In [25]:
print(df.shape)  # Number of rows and columns

(5, 3)


In [26]:
print(df.columns)  # Column names

Index(['Name', 'Age', 'Country'], dtype='object')


In [27]:
print(df.index)  # Index range

RangeIndex(start=0, stop=5, step=1)


In [29]:
print(df.dtypes)  # Data types of columns

Name       object
Age         int64
Country    object
dtype: object


In [31]:
print(df.describe())  # Summary statistics

             Age
count   5.000000
mean   28.000000
std     4.949747
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    35.000000


### Create a Pandas DataFrame with the following data

In [33]:
import pandas as pd

df = pd.read_csv("task1.csv")
print(df.head())

print("First 5 rows:")
print(df.head())

print("\nLast 10 rows:")
print(df.tail(10))

print("\nDataFrame Info:")
print(df.info())

print("\nShape of DataFrame:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nIndex Range:")
print(df.index)

print("\nData Types of Each Column:")
print(df.dtypes)

print("\nSummary Statistics (Numeric Columns):")
print(df.describe())

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   28  Female
First 5 rows:
     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   28  Female

Last 10 rows:
     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   28  Female

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

Shape of DataFrame:
(3, 3)

Column Names:
Index(['Name', 'Age', 'Gender'], dtype='object')

Index Range:
RangeIndex(start=0, stop=3, step=1)

Data Types of Each Column:
Name      object
Age        int64
Gender    object
dtype: object

Summary Statistics (Numeric Columns):
             Age
count   3.000000
mean   27.666667
std     2.516

In [36]:
import pandas as pd

# Define the dictionary
data = {'Name': ['Tom', 'Jerry', 'Mickey'],
        'Age': [20, 21, 22],
        'Gender': ['Male', 'Male', 'Female']}

# Create a DataFrame
df = pd.DataFrame(data)
print(df.shape)

(3, 3)


### From the DataFrame created above, filter and display rows where Age is greater than 25

In [37]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Claire'],
        'Age': [25, 30, 28],
        'Gender': ['Female', 'Male', 'Female']}
df = pd.DataFrame(data)
filtered_df = df[df['Age'] > 25]
print(filtered_df)

     Name  Age  Gender
1     Bob   30    Male
2  Claire   28  Female


### Add a new column 'salary' to the DataFrame with the following data: [50000, 60000, 70000]

In [38]:
df['Salary'] = [50000, 60000, 70000]
print(df)

     Name  Age  Gender  Salary
0   Alice   25  Female   50000
1     Bob   30    Male   60000
2  Claire   28  Female   70000


### Group the DataFrame by gender and calculate the average age in each gender

In [39]:
avg_age_by_gender = df.groupby('Gender')['Age'].mean()
print(avg_age_by_gender)

Gender
Female    26.5
Male      30.0
Name: Age, dtype: float64


### Sort the DataFrame based on the 'Age' column in descending order

In [40]:
sorted_df = df.sort_values('Age', ascending=False)
print(sorted_df)

     Name  Age  Gender  Salary
1     Bob   30    Male   60000
2  Claire   28  Female   70000
0   Alice   25  Female   50000
